name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install clasp
      run: npm install -g @google/clasp

    - name: Create project-level .clasp.json
      run: |
        echo '{"scriptId":"1-e_AIny8V-y5A5c2V5jD362_soMPyPzG22a91dsJg-sCJJLh2s2pDI6v","rootDir":"./src"}' > .clasp.json

    - name: Create clasp credentials file
      run: echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json

    - name: Push to Apps Script
      run: clasp push --force
