name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup clasp
        uses: google/clasp-action@v2
        with:
          creds: ${{ secrets.CLASPRC_JSON }}
      - name: Deploy
        run: clasp push -f
        working-directory: ./src
